### PR TITLE
whitelisting: add usbguard actions (bsc#1196621)

### PR DESCRIPTION
**Pull request by mgerstner**

### CODE REVIEW

**Review by jsegitz — APPROVED** [review]

**Comment by lnussel** [comment]
Why is auth_self suddenly ok? Where was that change discussed?

**Comment by mgerstner** [comment]
> Why is auth_self suddenly ok? Where was that change discussed?

This is coming from the upstream policy and it only affects read-only operations.

**Comment by lnussel** [comment]
yeah obviously it's upstream. They may use other distros and have defaults that match that. What about consistency in openSUSE? If the operations are read only, what's the security gain from entering your own password?

**Comment by mgerstner** [comment]
> yeah obviously it's upstream. They may use other distros and have defaults that match that. What about consistency in openSUSE? If the operations are read only, what's the security gain from entering your own password?

I fear there is no consistency to speak of, Polkit and its consumers don't make that very easy.
The standard profile generally should match upstream. So we could relax that in the easy profile. Maybe upstream is a bit too careful in this regard, especially since they had issues with that D-Bus interface in the past.

**Comment by lnussel** [comment]
Well, yes if you just use upstream values then there is no consistency. GIGO. Those profiles exists to create consistency for the distro.
IMO if calling those methods reveal information or does things that are not meant to be done by users, not even local ones then pk needs to ask for the root password. If that's not the case then no reason to ask. I just can't see the value of entering your own password. That concept doesn't exist on openSUSE.

**Pull request merged**
