### PR TITLE
Switching from /etc to /usr/etc directory

### PR DESCRIPTION
**Pull request by schubi2**
Moving polkit-default-privs.easy, polkit-default-privs.local and polkit-default-privs.restrictive from /etc /to /usr/etc directory.

### CODE REVIEW

**Comment by mgerstner** [comment]
Thank your for helping out and contributing.

Could you please remove these two `test` commits?

Should we maybe also keep a live version of `/etc/polkit-default-privs.local` that can be edited right away?

I wonder if we should use this opportunity to introduce a sub-directory to avoid these long path names. Something like:

```
/usr/etc/polkit-default-privs/profiles/easy
/usr/etc/polkit-default-privs/profiles/standard
/usr/etc/polkit-default-privs/profiles/restrictive
/usr/etc/polkit-default-privs/templates/local
```

What do you think @jsegitz, @wfrisch, @thesp0nge ?

**Comment by thesp0nge** [comment]
>  I wonder if we should use this opportunity to introduce a sub-directory to avoid these long path names.

I do really like the idea. It gives a cleaner filesystem layout

**Comment by wfrisch** [comment]
> > I wonder if we should use this opportunity to introduce a sub-directory to avoid these long path names.
> 
> I do really like the idea. It gives a cleaner filesystem layout

I agree. This is a good opportunity to reduce the clutter in (/usr)/etc/.

**Comment by mgerstner** [comment]
This is now covered via #53. Closing.

**Comment by schubi2** [comment]
Thanks for taking care !!!

**Pull request closed without merging**
