### PR TITLE
Add systemd homed (boo#1185285)

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Review by thesp0nge — CHANGES_REQUESTED** [review]
Can you please change from auth_admin_keep to auth_admin please?

**Comment by mgerstner** [comment]
> Can you please change from auth_admin_keep to auth_admin please?

Not everywhere, only in the restrictive profile. If it does not have any major usability issues that you know of.

**Comment by lnussel** [comment]
When do you use keep and when not?

    $ grep -c auth_admin_keep profiles/polkit-default-privs.restrictive
    296

**Comment by thesp0nge** [comment]
Hi @lnussel I know there are some over permissive settings, how ever I think that for homed in a scenario for restrict profile, should have only auth_admin. Do you think this could break something?

**Comment by mgerstner** [comment]
> When do you use keep and when not?
> 
> ```
> $ grep -c auth_admin_keep profiles/polkit-default-privs.restrictive
> 296
> ```

This is decided on a case by case basis. A long time no clear structure was followed. But we try to decide for each new entry consciously. The decision can be based on multiple factors:

- how often authentication will become necessary
- how good the code quality is
- the degrees of freedom that an action implies
- how well the software can cope with settings diverging from upstream default. E.g. flatpak, packagekit don't cope well with that resulting in a series of authentication popups for what looks like a single user action. Or authentication popups out of the blue right after login.

**Comment by lnussel** [comment]
So what's the point of randomly changing this one then? Anyway if that is the blocker feel free to accept and then "fix" up.

**Review by thesp0nge — APPROVED** [review]
for profiles/polkit-default-privs.restrictive profile must be set to auth_admin

**Comment by mgerstner** [comment]
I merged Paolos PR #43 with the adjusted settings.

**Pull request closed without merging**
